# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: laxman45
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: vinayaka-prod
# "service" is the name of this project. This will also be added to your AWS resource names.
service: vinayaka

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.12
  stage: prod

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - .git/** 
    - .serverless/** 
    - README.md
