name: FE dev deployment

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: 'employees-app'
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: pwd

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.REGION_NAME}}

      - name: Deploy to S3 bucket
        run: sls deploy
