name: FE dev deployment

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: 'AKE7Spo0cziBTpOtB3cH8K2GNJGUWbnwNUuMDsEiMQWYR'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Check current directory
        run: pwd

      - name: Update apt packages
        run: apt update
      - name: Install python
        run: Install python3.12
      - name: Install PIP
        run: python -m ensurepip –upgrade
        
      - name: Check current directory
        run: npm install -g serverless
      - name: Install python packages
        run: pip install -r requirements.txt
        
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.REGION_NAME}}

      - name: Deploy to AWS lambda
        run: serverless deploy
        
