name: BE dev deployment

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: 'AKE7Spo0cziBTpOtB3cH8K2GNJGUWbnwNUuMDsEiMQWYR'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install node dependencies
        run: npm install
        
      - name: Install Python 3.12
        run: |
          sudo apt update
          sudo apt install -y wget build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libbz2-dev libffi-dev
          wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
          tar -xf Python-3.12.0.tgz
          cd Python-3.12.0
          ./configure --enable-optimizations
          make
          sudo make altinstall
          sudo update-alternatives --install /usr/bin/python python /usr/local/bin/python3.12 1
          sudo update-alternatives --install /usr/bin/pip pip /usr/local/bin/pip3.12 1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.REGION_NAME}}

      - name: Deploy to AWS lambda
        run: serverless deploy
